### ISSUE TITLE
Multiple search item selection

### ISSUE THREAD

**Issue by rosselton** [NewcastleRSE/british-printed-images#16]
### Summary

The current site allows the selection and 'holding' of multiple items while searching the database. The 'hold' option appears once date range is selected and if used will 'pin' a selected item to the top of the search options. Multiple items can be selected and held (pinned) in this way. It does appear though that any images brought back by the original date search are not then accessible, being replaced by the last result set. 

### What needs to be done?

This functionality needs to be reviewed. Discussion is needed to determine the best way to implementing a similar solution. I think it would be better to allow the user to access previous selected images in some way, rather than be restricted to viewing the last set returned. This could be done by creating a gallery of some sort where the user can choose to keep or delete items.

### Who can help?

Adam Morton, Tiago Sousa Garcia

### Which user story does this task relate to?

#13 #14 #11

**Comment by AdamMorton1982** [comment]
Hello Becky,

This feature is unclear. I think 'hold' is misleading. I have tried multiple times to use it to retain an old search, to no avail. I wonder if it is actually a 'filter' rather than a 'hold' (making a current search more focussed, rather than helping to save it). For example, if I go to subject a click 'Society', I get 1245 results. If I then change the date range and click 'hold' the results narrow; if I go to technique, select 'engraving' and 'hold' it narrows again. To my mind, this is a filter. Does describing it as such make it clearer?

I may be wrong, but I can see no way of saving searches.

**Comment by rosselton** [comment]
Yes, agreed  - it functions as a result filter, although this isn't very obvious to the user. We need to find a more intuitive solution that reproduces the same functionality.

**Comment by rosselton** [comment]
Main searches finalised
