### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by rosselton** [NewcastleRSE/british-printed-images#8]
### Summary

The About section contains sub-section links:

* The corpus
* The database
* the subject index
* credits

### What needs to be done?

The information needs to be reviewed for accuracy and updated. The credit section might be better suited to another location on the website or in a modal window accessible from the footer.

In the Corpus section, the page is too text heavy so a method should be found to break it into more accessible sections (or multiple pages) Some of the embedded links could be listed separately as well as in the page content.

### Who can help?

Adam Morton

### Which user story does this task relate to?

#1

**Comment by AdamMorton1982** [comment]
Hello Becky,

Yes, this section needs updating. It is too text-heavy, so will need pruning. A couple of thoughts:

1) Credits. Do we need this? The info is now out of date. It seems to me that a couple of sentences in 'About' would suffice.
2) Subject Index. What we do with this depends on what we can do with the search function of the database. If it is possible to make searching freer (i.e type a term and up the material pops) then a long page explaining the subjects seem less important. As it stands, this page seems to exist to justify the choices of the original project team. Pruning it to focus on how a user might use the subject terms seems more sensible. What do you think?
3) Does it also make sense to combine the information in 'Database' and 'Subject Index'? Again, with the focus being on how someone might use the database rather than explaining how it was created?
